title: Jiahui Huang
description: Personal Website
url: https://jiahuihuang.me
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

locale: zh-CN
permalink: /:categories/:title/

author:
  name: Jiahui Huang
  avatar: 
  bio: 
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:"
    - label: "Blog"
      icon: "fas fa-link"
      url: "https://helloaisvg.cn"

paginate: 5
paginate_path: /page:num/

collections:
  research:
    output: true
    permalink: /research/:path/
  publications:
    output: true
    permalink: /publications/:path/

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock


